#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements
# localhost from 127.0.0.1 to 127.0.0.2.
# facebook.com from 157.240.11.35 to 8.8.8.8.

# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Update hosts file to set localhost to 127.0.0.2
echo "127.0.0.2 localhost" >> /etc/hosts
#facebook.com to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Hosts file updated successfully."
