#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements
# localhost from 127.0.0.1 to 127.0.0.2.
# facebook.com from 157.240.11.35 to 8.8.8.8

# Create a new hosts file with the specified entries
echo "127.0.0.2     localhost" > ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new

# Replace the existing hosts file with the new one
sudo cp -f ~/hosts.new /etc/hosts

echo "Hosts file updated successfully."
